
service: aws-nodejs # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-offline


functions:
  mongoInsert:
    handler: api/api.mongoInsert
    events :
      - http:
          path : /api
          method : POST



